[
  {
    "term": "Fall 2026",
    "course_code": "CS 1301",
    "section": "03",
    "title": "Programming Principles",
    "professor_id": "p100",
    "professor_name": "Prof. A. Smith",
    "campus": "Marietta",
    "modality": "In Person",
    "days": "TR",
    "time": "11:00 AM - 12:15 PM",
    "seats_available": 18,
    "crn": "61234"
  },
  {
    "term": "Fall 2026",
    "course_code": "CS 1302",
    "section": "04",
    "title": "Data Structures",
    "professor_id": "p101",
    "professor_name": "Dr. N. Patel",
    "campus": "Marietta",
    "modality": "Hybrid",
    "days": "MW",
    "time": "2:00 PM - 3:15 PM",
    "seats_available": 7,
    "crn": "61235"
  },
  {
    "term": "Fall 2026",
    "course_code": "CSE 1321",
    "section": "02",
    "title": "Programming and Problem Solving I",
    "professor_id": "p101",
    "professor_name": "Dr. N. Patel",
    "campus": "Marietta",
    "modality": "In Person",
    "days": "MW",
    "time": "9:30 AM - 10:45 AM",
    "seats_available": 3,
    "crn": "61239"
  },
  {
    "term": "Fall 2026",
    "course_code": "CSE 1321",
    "section": "03",
    "title": "Programming and Problem Solving I",
    "professor_id": "p100",
    "professor_name": "Prof. A. Smith",
    "campus": "Marietta",
    "modality": "Hybrid",
    "days": "TR",
    "time": "3:30 PM - 4:45 PM",
    "seats_available": 10,
    "crn": "61240"
  },
  {
    "term": "Fall 2026",
    "course_code": "CSE 1322",
    "section": "02",
    "title": "Programming and Problem Solving II",
    "professor_id": "p101",
    "professor_name": "Dr. N. Patel",
    "campus": "Marietta",
    "modality": "In Person",
    "days": "TR",
    "time": "12:30 PM - 1:45 PM",
    "seats_available": 6,
    "crn": "61241"
  },
  {
    "term": "Fall 2026",
    "course_code": "DATA 1501",
    "section": "02",
    "title": "Introduction to Data Science",
    "professor_id": "p201",
    "professor_name": "Dr. S. Lopez",
    "campus": "Online",
    "modality": "Online Async",
    "days": "TBA",
    "time": "TBA",
    "seats_available": 14,
    "crn": "61244"
  },
  {
    "term": "Fall 2026",
    "course_code": "DATA 3201",
    "section": "01",
    "title": "Applied Modeling",
    "professor_id": "p201",
    "professor_name": "Dr. S. Lopez",
    "campus": "Online",
    "modality": "Online Async",
    "days": "TBA",
    "time": "TBA",
    "seats_available": 11,
    "crn": "61237"
  },
  {
    "term": "Fall 2026",
    "course_code": "IS 2200",
    "section": "04",
    "title": "Information Systems and Communication",
    "professor_id": "p401",
    "professor_name": "Dr. K. Evans",
    "campus": "Kennesaw",
    "modality": "Hybrid",
    "days": "TR",
    "time": "6:30 PM - 7:45 PM",
    "seats_available": 11,
    "crn": "61243"
  },
  {
    "term": "Fall 2026",
    "course_code": "IS 3260",
    "section": "05",
    "title": "Business Application Development",
    "professor_id": "p400",
    "professor_name": "Prof. M. Chen",
    "campus": "Kennesaw",
    "modality": "In Person",
    "days": "MW",
    "time": "12:30 PM - 1:45 PM",
    "seats_available": 16,
    "crn": "61238"
  },
  {
    "term": "Fall 2026",
    "course_code": "MATH 1190",
    "section": "09",
    "title": "Calculus I",
    "professor_id": "p300",
    "professor_name": "Dr. J. Turner",
    "campus": "Kennesaw",
    "modality": "In Person",
    "days": "MWF",
    "time": "10:00 AM - 10:50 AM",
    "seats_available": 8,
    "crn": "61242"
  },
  {
    "term": "Fall 2026",
    "course_code": "MATH 2202",
    "section": "02",
    "title": "Calculus II",
    "professor_id": "p300",
    "professor_name": "Dr. J. Turner",
    "campus": "Kennesaw",
    "modality": "In Person",
    "days": "TR",
    "time": "8:00 AM - 9:15 AM",
    "seats_available": 0,
    "crn": "61236"
  },
  {
    "term": "Spring 2027",
    "course_code": "CS 2302",
    "section": "01",
    "title": "Discrete Structures",
    "professor_id": "p102",
    "professor_name": "Dr. R. Greene",
    "campus": "Marietta",
    "modality": "In Person",
    "days": "TR",
    "time": "12:30 PM - 1:45 PM",
    "seats_available": 14,
    "crn": "71231"
  },
  {
    "term": "Spring 2027",
    "course_code": "CS 3304",
    "section": "01",
    "title": "Mathematical Foundations of Computing",
    "professor_id": "p102",
    "professor_name": "Dr. R. Greene",
    "campus": "Marietta",
    "modality": "In Person",
    "days": "TR",
    "time": "2:00 PM - 3:15 PM",
    "seats_available": 9,
    "crn": "71232"
  },
  {
    "term": "Spring 2027",
    "course_code": "CS 3502",
    "section": "01",
    "title": "Operating Systems",
    "professor_id": "p102",
    "professor_name": "Dr. R. Greene",
    "campus": "Marietta",
    "modality": "In Person",
    "days": "MW",
    "time": "11:00 AM - 12:15 PM",
    "seats_available": 12,
    "crn": "71234"
  },
  {
    "term": "Spring 2027",
    "course_code": "CS 3600",
    "section": "01",
    "title": "Systems and Architecture",
    "professor_id": "p102",
    "professor_name": "Dr. R. Greene",
    "campus": "Marietta",
    "modality": "Hybrid",
    "days": "TR",
    "time": "9:30 AM - 10:45 AM",
    "seats_available": 6,
    "crn": "71235"
  },
  {
    "term": "Spring 2027",
    "course_code": "DATA 2201",
    "section": "02",
    "title": "Data Wrangling",
    "professor_id": "p201",
    "professor_name": "Dr. S. Lopez",
    "campus": "Online",
    "modality": "Online Async",
    "days": "TBA",
    "time": "TBA",
    "seats_available": 17,
    "crn": "71238"
  },
  {
    "term": "Spring 2027",
    "course_code": "DATA 4101",
    "section": "01",
    "title": "Data Science Project",
    "professor_id": "p201",
    "professor_name": "Dr. S. Lopez",
    "campus": "Online",
    "modality": "Online Async",
    "days": "TBA",
    "time": "TBA",
    "seats_available": 15,
    "crn": "71236"
  },
  {
    "term": "Spring 2027",
    "course_code": "IS 2200",
    "section": "03",
    "title": "Information Systems and Communication",
    "professor_id": "p400",
    "professor_name": "Prof. M. Chen",
    "campus": "Kennesaw",
    "modality": "In Person",
    "days": "TR",
    "time": "11:00 AM - 12:15 PM",
    "seats_available": 19,
    "crn": "71237"
  },
  {
    "term": "Spring 2027",
    "course_code": "IS 3700",
    "section": "02",
    "title": "Business Intelligence",
    "professor_id": "p401",
    "professor_name": "Dr. K. Evans",
    "campus": "Kennesaw",
    "modality": "Hybrid",
    "days": "MW",
    "time": "4:00 PM - 5:15 PM",
    "seats_available": 5,
    "crn": "71233"
  },
  {
    "term": "Summer 2026",
    "course_code": "CSE 1322",
    "section": "01",
    "title": "Programming and Problem Solving II",
    "professor_id": "p101",
    "professor_name": "Dr. N. Patel",
    "campus": "Marietta",
    "modality": "In Person",
    "days": "MW",
    "time": "9:30 AM - 10:45 AM",
    "seats_available": 4,
    "crn": "50123"
  },
  {
    "term": "Summer 2026",
    "course_code": "DATA 2201",
    "section": "W01",
    "title": "Data Wrangling",
    "professor_id": "p201",
    "professor_name": "Dr. S. Lopez",
    "campus": "Online",
    "modality": "Online Async",
    "days": "TBA",
    "time": "TBA",
    "seats_available": 12,
    "crn": "50456"
  }
]